[package]
name = "hacspec_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
natmod.workspace = true
num-bigint = "0.4.3"
num-traits = "0.2.15"