[package]
name = "natmod"
version = "0.1.0"
edition = "2021"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
hex = "0.4.3"
num-bigint = "0.4.3"
quote = "1.0.28"
syn = { version = "2.0.18", features = ["full"] }
