[package]
name = "prp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hacspec_lib.workspace = true

[dev-dependencies]
rand = "0.8.5"
