[package]
name = "oprf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
natmod.workspace = true
p256.workspace = true
hash-to-curve.workspace = true
elgamal.workspace = true
hacspec_lib.workspace = true
sha256.workspace = true

[dev-dependencies]
serde_json.workspace = true
hex = { version = "0.4.3", features = ["serde"] }
serde.workspace = true
log = "0.4.19"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
